# Generated by Django 5.2.16 on 2026-08-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_donation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=150)),
                ("event_date", models.DateField()),
                ("description", models.TextField()),
            ],
        ),
    ]
