# Generated by Django 5.2.16 on 2026-08-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=255)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("order", models.IntegerField()),
                ("status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Initiative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                ("image_url", models.URLField(max_length=150)),
                ("order", models.IntegerField()),
                ("status", models.TextField(default="Active")),
            ],
        ),
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=50)),
                ("order", models.CharField(max_length=150)),
                ("status", models.CharField(default="Active", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="VisionMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vision_title", models.CharField(max_length=150)),
                ("vision_description", models.CharField(max_length=200)),
                ("mission_title", models.CharField(max_length=150)),
                ("mission_description", models.CharField(max_length=200)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
