# Generated by Django 4.2.30 on 2026-08-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagegallery",
            name="image",
            field=models.ImageField(upload_to="gallery/"),
        ),
    ]
